import SwiftUI

/// Legal Disclaimer Screen — user MUST agree before using the app.
/// Shows automatically on first launch. Cannot be bypassed or dismissed.
/// User must check BOTH agreement boxes before the Continue button activates.
/// Persisted via @AppStorage — only shows once per install.
struct DisclaimerView: View {
    @Binding var hasAgreed: Bool
    @State private var agreesDisclaimer = false
    @State private var agreesNotMedical = false
    @State private var showError = false
    @State private var shakeOffset: CGFloat = 0

    private var bothChecked: Bool {
        agreesDisclaimer && agreesNotMedical
    }

    var body: some View {
        ZStack {
            // Background — completely opaque, no tapping through
            Color(red: 0.06, green: 0.04, blue: 0.12)
                .ignoresSafeArea()

            LinearGradient(
                colors: [
                    Color(red: 0.08, green: 0.06, blue: 0.14),
                    Color(red: 0.12, green: 0.08, blue: 0.18),
                    Color(red: 0.06, green: 0.04, blue: 0.12)
                ],
                startPoint: .top,
                endPoint: .bottom
            )
            .ignoresSafeArea()

            ScrollView {
                VStack(spacing: 24) {
                    Spacer(minLength: 50)

                    // Header
                    VStack(spacing: 12) {
                        Image(systemName: "shield.checkered")
                            .font(.system(size: 48))
                            .foregroundColor(Color(red: 0.9, green: 0.7, blue: 0.3))
                            .shadow(color: Color(red: 0.9, green: 0.7, blue: 0.3).opacity(0.3), radius: 10)

                        Text("Important Disclaimer")
                            .font(.system(size: 28, weight: .bold, design: .serif))
                            .foregroundColor(.white)

                        Text("You must read and agree before using MySoulSpeak")
                            .font(.system(size: 14, weight: .medium))
                            .foregroundColor(.white.opacity(0.6))
                            .multilineTextAlignment(.center)
                    }

                    // Disclaimer content
                    VStack(alignment: .leading, spacing: 16) {
                        disclaimerSection(
                            title: "Not a Medical Service",
                            text: "MySoulSpeak is a wellness and self-reflection app designed for entertainment and general wellness purposes ONLY. It is NOT a substitute for professional medical advice, diagnosis, or treatment."
                        )

                        disclaimerSection(
                            title: "Fictional Characters",
                            text: "\"Dr. Hope\" and \"Mr. Hope\" are fictional AI-generated characters. They are NOT real licensed medical doctors, therapists, counselors, psychologists, or mental health professionals. No doctor-patient or therapist-client relationship is created by using this app."
                        )

                        disclaimerSection(
                            title: "No Professional Advice",
                            text: "Any responses, suggestions, or conversations provided by this app are generated by artificial intelligence and should NOT be considered professional medical, psychological, therapeutic, or counseling advice."
                        )

                        disclaimerSection(
                            title: "Crisis Resources",
                            text: "If you are experiencing a mental health crisis, suicidal thoughts, or any medical emergency, please immediately contact 911, the 988 Suicide & Crisis Lifeline, or your local emergency services. Do NOT rely on this app for crisis support."
                        )

                        disclaimerSection(
                            title: "Use at Your Own Risk",
                            text: "By using MySoulSpeak, you acknowledge that you use this app at your own risk. The creators, developers, and operators shall not be held liable for any damages, harm, or adverse effects resulting from the use of this application."
                        )

                        disclaimerSection(
                            title: "No Guarantee of Results",
                            text: "MySoulSpeak makes no guarantees regarding outcomes, improvements in mental health, or any specific results. Individual experiences may vary."
                        )

                        disclaimerSection(
                            title: "Data & Privacy",
                            text: "Your voice recordings, journal entries, and mood data are stored locally on your device. AI conversation data may be processed through third-party APIs subject to their respective privacy policies."
                        )
                    }
                    .padding(20)
                    .background(
                        RoundedRectangle(cornerRadius: 16)
                            .fill(Color.white.opacity(0.04))
                            .overlay(
                                RoundedRectangle(cornerRadius: 16)
                                    .stroke(Color.white.opacity(0.1), lineWidth: 1)
                            )
                    )

                    // MARK: - Agreement Checkboxes (BOTH required)
                    VStack(spacing: 16) {
                        // Checkbox 1: Read and understand
                        agreementCheckbox(
                            isChecked: $agreesDisclaimer,
                            text: "I have read and understand this disclaimer. I acknowledge that MySoulSpeak is for wellness/entertainment purposes only and does NOT provide real medical or therapeutic services."
                        )

                        // Checkbox 2: Characters are fictional
                        agreementCheckbox(
                            isChecked: $agreesNotMedical,
                            text: "I understand that \"Dr. Hope\" and \"Mr. Hope\" are fictional AI characters — NOT real healthcare professionals — and I will seek real professional help for serious mental health needs."
                        )
                    }
                    .padding(.top, 8)

                    // Error message
                    if showError {
                        HStack(spacing: 6) {
                            Image(systemName: "exclamationmark.triangle.fill")
                                .font(.system(size: 13))
                            Text("You must check both boxes to continue")
                                .font(.system(size: 13, weight: .semibold))
                        }
                        .foregroundColor(.red)
                        .padding(.vertical, 8)
                        .padding(.horizontal, 16)
                        .background(
                            Capsule()
                                .fill(Color.red.opacity(0.1))
                        )
                        .transition(.opacity.combined(with: .scale(scale: 0.95)))
                    }

                    // MARK: - Continue Button (disabled until both checked)
                    Button(action: attemptContinue) {
                        HStack(spacing: 10) {
                            if bothChecked {
                                Image(systemName: "checkmark.shield.fill")
                                    .font(.system(size: 16))
                            }
                            Text(bothChecked ? "I Agree — Continue" : "Check Both Boxes to Continue")
                                .font(.system(size: 16, weight: .bold))
                        }
                        .foregroundColor(bothChecked ? .white : .white.opacity(0.3))
                        .frame(maxWidth: .infinity)
                        .padding(.vertical, 18)
                        .background(
                            RoundedRectangle(cornerRadius: 14)
                                .fill(bothChecked
                                      ? LinearGradient(colors: [Color(red: 0.7, green: 0.4, blue: 0.8), Color(red: 0.5, green: 0.25, blue: 0.7)], startPoint: .leading, endPoint: .trailing)
                                      : LinearGradient(colors: [Color.white.opacity(0.08), Color.white.opacity(0.04)], startPoint: .leading, endPoint: .trailing)
                                )
                        )
                    }
                    .disabled(!bothChecked)
                    .offset(x: shakeOffset)
                    .padding(.top, 8)

                    // Legal footer
                    Text("Last updated: August 2026 | Version 1.0")
                        .font(.system(size: 10))
                        .foregroundColor(.white.opacity(0.3))
                        .padding(.bottom, 40)
                }
                .padding(.horizontal, 24)
            }
        }
        .interactiveDismissDisabled(true)
    }

    // MARK: - Attempt Continue
    private func attemptContinue() {
        if bothChecked {
            withAnimation(.easeInOut(duration: 0.3)) {
                hasAgreed = true
            }
        } else {
            // Shake the button
            withAnimation(.spring(response: 0.1, dampingFraction: 0.3)) {
                shakeOffset = 10
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
                withAnimation(.spring(response: 0.1, dampingFraction: 0.3)) {
                    shakeOffset = -10
                }
            }
            DispatchQueue.main.asyncAfter(deadline: .now() + 0.2) {
                withAnimation(.spring(response: 0.1, dampingFraction: 0.5)) {
                    shakeOffset = 0
                }
            }
            withAnimation(.spring(response: 0.3)) {
                showError = true
            }
        }
    }

    // MARK: - Agreement Checkbox
    private func agreementCheckbox(isChecked: Binding<Bool>, text: String) -> some View {
        Button(action: {
            withAnimation(.spring(response: 0.3, dampingFraction: 0.7)) {
                isChecked.wrappedValue.toggle()
                showError = false
            }
        }) {
            HStack(alignment: .top, spacing: 14) {
                // Checkbox
                ZStack {
                    RoundedRectangle(cornerRadius: 6)
                        .stroke(isChecked.wrappedValue ? Color(red: 0.4, green: 0.85, blue: 0.5) : Color.white.opacity(0.4), lineWidth: 2)
                        .frame(width: 28, height: 28)

                    if isChecked.wrappedValue {
                        RoundedRectangle(cornerRadius: 6)
                            .fill(Color(red: 0.4, green: 0.85, blue: 0.5))
                            .frame(width: 28, height: 28)

                        Image(systemName: "checkmark")
                            .font(.system(size: 15, weight: .bold))
                            .foregroundColor(.white)
                    }
                }

                // Text
                Text(text)
                    .font(.system(size: 13, weight: .medium))
                    .foregroundColor(.white.opacity(0.85))
                    .multilineTextAlignment(.leading)
                    .lineSpacing(3)
            }
        }
    }

    // MARK: - Disclaimer Section
    private func disclaimerSection(title: String, text: String) -> some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 8) {
                Circle()
                    .fill(Color(red: 0.9, green: 0.7, blue: 0.3))
                    .frame(width: 6, height: 6)
                Text(title)
                    .font(.system(size: 14, weight: .bold))
                    .foregroundColor(.white)
            }

            Text(text)
                .font(.system(size: 12, weight: .regular))
                .foregroundColor(.white.opacity(0.75))
                .lineSpacing(3)
        }
    }
}
